name: "Bot: Write comment about Azure Pipelines"

on:
  pull_request:
    branches:
      - 'master'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: rytswd/respost@v0.1.0
        with:
          body: /azp run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
